name: Multiplatform Build with QEMU

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    permissions: # needed for signing and attestations
     id-token: write # write seems weird, but it is correct per docs
     attestations: write
     contents: read
     packages: write

    runs-on: ubuntu-latest

    steps:
      - 
        name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
      -
        name: Set up QEMU
        uses: chainguard-actions/docker-setup-qemu-action@e618b09f0e92c964c8968525b00939e800efb8f5 # v4.0.0
      -
        name: Set up Docker Buildx
        uses: chainguard-actions/docker-setup-buildx-action@8fbaa429a8f774ef64700ee4749056cd9aba100b # v3
      -
        name: Login to GitHub Container Registry
        uses: chainguard-actions/docker-login-action@c4e74ea6a0c39bc863791d3b4b737e06e93d4da7 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@4f5b5234679dfa19837d4942067c97d7df43b7b3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-qemu
          labels: |
            org.opencontainers.image.description=Demo QEMU Build
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Attest
        uses: chainguard-actions/actions-attest-build-provenance@ba968bd7c54b40a4f8c43282db9943c6a6332327 # v4.1.0
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-qemu
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
      - 
        name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
