# Copyright 2026 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Zizmor

on:
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      actions: read # Required by codeql-action/upload-sarif to get workflow run info
      contents: read # Clone the repository
      security-events: write # Upload SARIF results to Code Scanning
    steps:

      - name: Check out code
        uses: chainguard-actions/actions-checkout@a42eec69c968e4ee261d1a2f03543e4198ac21b3 # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: chainguard-actions/zizmorcore-zizmor-action@a82b960df159875a8dd2683df999f1b8ab188f31 # v0.5.2
